//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SambariEnterprises.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public long ID { get; set; }
        public System.Guid ResourceID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string HashCode { get; set; }
        public string EmailID { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public long RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
